version: 2
updates:
  - package-ecosystem: "dotnet-sdk"
    directory: "/"
    schedule:
      interval: "daily"
    cooldown:
      default-days: 7
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    cooldown:
      default-days: 7
  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "System.CommandLine" # https://github.com/dotnet/command-line-api/issues/2763
    cooldown:
      default-days: 7
    groups:
      xunit:
        patterns:
          - "xunit"
          - "xunit.*"
