<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <NoWarn>$(NoWarn);CA1515</NoWarn>    <!-- Consider making public types internal -->
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../../src/Bullseye/Bullseye.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="System.CommandLine" />
  </ItemGroup>

</Project>
