trigger:
  branches:
    include:
      - main
      - release-*
jobs:
  - job: Windows
    pool:
      vmImage: "windows-2022"
    steps:
      - task: UseDotNet@2
        inputs:
          version: "6.0.100"
      - script: dotnet --info
        displayName: "Display .NET Core information."
      - script: ./build.cmd
        displayName: "Build the project"
  - job: Linux
    pool:
      vmImage: "ubuntu-20.04"
    steps:
      - task: UseDotNet@2
        inputs:
          version: "6.0.100"
      - script: dotnet --info
        displayName: "Display .NET Core information."
      - script: ./build.sh
        displayName: "Build the project"
  - job: macOS
    pool:
      vmImage: "macOS-11"
    steps:
      - task: UseDotNet@2
        inputs:
          version: "6.0.100"
      - script: dotnet --info
        displayName: "Display .NET Core information."
      - script: ./build.sh
        displayName: "Build the project"
