<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="PublicApiGenerator" Version="11.5.4" />
  </ItemGroup>

  <ItemGroup>
    <None Update="OutputTests.*.verified.txt">
      <DependentUpon>OutputTests.cs</DependentUpon>
    </None>
    <None Update="PublicApi.*.verified.txt">
      <DependentUpon>PublicApi.cs</DependentUpon>
    </None>
  </ItemGroup>

</Project>
