<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="../../fixtures/Fixtures.Xunit/Fixtures.Xunit.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="PublicApiGenerator" />
  </ItemGroup>

  <ItemGroup>
    <None Update="OutputTests.*.expected.txt">
      <DependentUpon>OutputTests.cs</DependentUpon>
    </None>
    <None Update="PublicApi.*.expected.txt">
      <DependentUpon>PublicApi.cs</DependentUpon>
    </None>
  </ItemGroup>

</Project>
