<Project>

  <Import Project="$([MSBuild]::GetPathOfFileAbove('Directory.Build.props', '$(MSBuildThisFileDirectory)..\'))" />

  <PropertyGroup>
    <IsPackable>false</IsPackable>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>

  <PropertyGroup>
    <NoWarn>$(NoWarn);CA1034</NoWarn>    <!-- Nested types should not be visible --><!-- workaround for https://github.com/dotnet/roslyn-analyzers/issues/7734 -->
    <NoWarn>$(NoWarn);CA1062</NoWarn>    <!-- Validate arguments of public methods -->
    <NoWarn>$(NoWarn);CA1515</NoWarn>    <!-- Consider making public types internal --><!-- workaround for https://github.com/dotnet/roslyn-analyzers/issues/7734 -->
    <NoWarn>$(NoWarn);CS1591</NoWarn>    <!-- Missing XML comment for publicly visible type or member --><!-- workaround for https://github.com/dotnet/roslyn/issues/41640 -->
    <NoWarn>$(NoWarn);CA2007</NoWarn>    <!-- Do not directly await a Task -->
    <NoWarn>$(NoWarn);VSTHRD111</NoWarn>    <!-- Add .ConfigureAwait(bool) to your await expression -->
  </PropertyGroup>

</Project>
