<Project>

  <Import Project="$([MSBuild]::GetPathOfFileAbove('Directory.Build.props', '$(MSBuildThisFileDirectory)..\'))" />

  <Sdk Name="DotNet.ReproducibleBuilds.Isolated" Version="2.0.5" />

  <PropertyGroup>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <PackageIcon>icon.png</PackageIcon>
    <PackageLicenseExpression>Apache-2.0</PackageLicenseExpression>
    <PackageProjectUrl>https://github.com/adamralph/bullseye</PackageProjectUrl>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <PackageReleaseNotes>https://github.com/adamralph/bullseye/blob/main/CHANGELOG.md</PackageReleaseNotes>
  </PropertyGroup>

  <PropertyGroup>
    <NoWarn>$(NoWarn);RS0016</NoWarn>    <!-- Add public types and members to the declared API -->
    <NoWarn>$(NoWarn);RS0037</NoWarn>    <!-- Enable tracking of nullability of reference types in the declared API -->
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)'=='Release'">
    <GenerateSBOM>true</GenerateSBOM>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="DotNet.ReproducibleBuilds" PrivateAssets="All" />
    <PackageReference Include="Microsoft.CodeAnalysis.PublicApiAnalyzers" PrivateAssets="All" />
    <PackageReference Include="Microsoft.Sbom.Targets" PrivateAssets="All" />
    <PackageReference Include="MinVer" PrivateAssets="All" />
  </ItemGroup>

  <ItemGroup>
    <None Include="../../assets/icon.png" Pack="true" PackagePath="/" />
    <None Include="../../README.md" Pack="true" PackagePath="/" />
  </ItemGroup>

</Project>
