name: release
on:
  push:
    tags: ["*.*.*"]
  workflow_dispatch:
permissions:
  id-token: write
env:
  DOTNET_NOLOGO: true
  MINVERBUILDMETADATA: build.${{ github.run_id }}.${{ github.run_attempt}}
jobs:
  release:
    runs-on: ubuntu-24.04-arm
    steps:
      - uses: actions/setup-dotnet@c2fa09f4bde5ebb9d1777cf28262a3eb3db3ced7 # v5.2.0
        with:
          dotnet-version: 10.0.201
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - run: ./build pack
      - uses: NuGet/login@8d196754b4036150537f80ac539e15c2f1028841 # v1
        id: nuget-login
        with:
          user: ${{ secrets.NUGET_USER }}
      - name: push
        env:
          API_KEY: ${{steps.nuget-login.outputs.NUGET_API_KEY}}
        run: dotnet nuget push ./artifacts/*.nupkg --api-key "$API_KEY" --source https://api.nuget.org/v3/index.json
